name: Run Cypress Tests in Parallel

on:
  push:
    branches:
      - '*'

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm install
      - name: Send Google Chat notification
          if:failure()
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
    "text": "Build Failed! Build ID: '${{ github.run_id }}', Repository name: ${{ github.repository }}, Workflow name: ${{ github.workflow }}",
    "cards": [
      {
        "header": {
          "title": "Build Failure"
        },
        "sections": [
          {
            "widgets": [
              {
                "textParagraph": {
                  "text": "Build Failed! Build ID: '${{ github.run_id }}', Repository name: ${{ github.repository }}, Workflow name: ${{ github.workflow }}"
                }
              },
              {
                "buttons": [
                  {
                    "textButton": {
                      "text": "View Failed Build",
                      "onClick": {
                        "openLink": {
                          "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                        }
                      }
                    }
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }' \
  "https://chat.googleapis.com/v1/spaces/AAAAx0jIx9E/messages?key=YOUR_API_KEY&token=YOUR_TOKEN"
      - name: Run Dev
        run: npm run dev
     

  prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm install

      - name: Run Prod
        run: npm run prod

  staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm install

      - name: Run Staging
        run: npm run staging
